### PR TITLE
Fis 111 write report button manager panel

### PR DESCRIPTION
**Pull request by hrvojevincek**
test the site by logging in and go to manager panel. <3

### CODE REVIEW

**Comment by bienmag** [comment]
the page is crashes when i go to dashboard or manager panel -> should be redirecting me to login page

**Comment by bienmag** [comment]
what's the point of this navigation? 
the user shouldn't see the manager panel.

**Comment by hrvojevincek** [comment]
> 

it was just for our testing purposes.

**Comment by hrvojevincek** [comment]
> the page crashes when i go to dashboard or manager panel -> should be redirecting me to login page

**Comment by hrvojevincek** [comment]
> the page crashes when i go to dashboard or manager panel -> should be redirecting me to login page

can we take this from your branch? since you have this functionality implemented?

**Comment by hrvojevincek** [comment]
changes implemented. if not logged in, you cant acces dashboard od manager panel

**Comment by hrvojevincek** [comment]
conflicts resolved. review. so i can merge

**Pull request closed without merging**
