### PR TITLE
Fis 14 create an account

### PR DESCRIPTION
**Pull request by hrvojevincek**
the signup is insecure btw as we discussed.

### CODE REVIEW

**Comment by bienmag** [comment]
image
should it look like this?

**Comment by craigostrin** [comment]
> image should it look like this?

YES ABSOLUTELY

old school 😎

**Comment by hrvojevincek** [comment]
how did you get this please explain? i have imported now global.css just in case ... let me know if it brakes agaiin

**Comment by craigostrin** [comment]
Hrvoe is redoing this as a new branch

**Pull request closed without merging**
