### PR TITLE
added error handler for checking if an email exists

### PR DESCRIPTION
**Pull request by Mutotu**
Modified graphql-queries.ts for  GET_USERS's properties where I added email . FIrst I check if the user with that email exists using this api and then if it does, error shows up saying user exists.

### CODE REVIEW

**Comment by bienmag** [comment]
I believe it does the job, but I think the logic should be implemented in the back end, so the front end only gets a new user if 200, or the error message 'email already used' instead of bringing all the users to the front end

**Comment by bienmag** [comment]
@craigostrin can you please take a look it it? want to hear your opinion

**Comment by Mutotu** [comment]
lol I think you're right Rita. The logic should be in the server. I've been trying it ou since yesterday but it takes half an hour for every console log I do beucase I need to kill the ports or reset the this and that..If that's needed right away, you guys are welcome to fix it lol.

**Comment by craigostrin** [comment]
Yeah I agree it should happen on the server.

I would say the server should do the check, then respond with an error message that the client should show.

**Comment by bienmag** [comment]
@Mutotu take your time.......

**Comment by Mutotu** [comment]
Aight...

**Review by bienmag — CHANGES_REQUESTED** [review]
error check should go to the server

**Comment by Mutotu** [comment]
Finally I added in the server and it works. If any changes need, please do it lol. Lo siento but laptop runs slower than a slug...

**Review by bienmag — APPROVED** [review]

**Comment by bienmag** [comment]
👍🏼

**Pull request merged**
